name: Deploy static site to Pages
on:
  push:
    branches: [master]
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Upload Pages artifact
        uses: gitverse://actions/upload-pages-artifact@v1
        with:
          path: '.'
      - name: Deploy to Pages
        uses: gitverse://actions/deploy-pages@v1
