name: Deploy to S3
on:
  push:
    branches: [master]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install rclone
        run: curl -s https://rclone.org/install.sh | sudo bash
      - name: Configure rclone
        run: |
          rclone config create ru-3 s3 \
            provider Selectel \
            env_auth false \
            access_key_id ${{ secrets.SELECTEL_KEY }} \
            secret_access_key ${{ secrets.SELECTEL_SECRET }} \
            region ru-3 \
            endpoint s3.ru-3.storage.selcloud.ru
      - name: Sync HTML & API to root
        run: |
          rclone sync . ru-3:storage-data \
            --include "*.html" --include "api/**" --exclude ".gitverse/**" --progress
