name: Deploy to S3
on:
  push:
    branches: [master]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install rclone
        run: curl -s https://rclone.org/install.sh | sudo bash
      - name: Configure rclone
        run: |
          rclone config create ru-3 s3 \
            provider Selectel \
            env_auth false \
            access_key_id ${{ secrets.SELECTEL_KEY }} \
            secret_access_key ${{ secrets.SELECTEL_SECRET }} \
            region ru-3 \
            endpoint s3.ru-3.storage.selcloud.ru
      - name: Sync HTML & API
        run: |
          rclone sync . ru-3:storage-data/glukhova-dasha \
            --include "*.html" --include "api/**" --progress
      - name: Sync images from repo
        run: |
          rclone sync originals ru-3:storage-data/glukhova-dasha/originals --progress
      - name: Sync images CDN path
        run: |
          rclone copy ru-3:storage-data/glukhova-dasha/originals \
            ru-3:storage-data/glukhova-dasha/originals/5479c8026bbe3ca75cc0a82e/3936815 \
            --progress
